set(GAMEWINDOW_SYSTEM_DEFAULT EGLUT)
if (APPLE)
    set(GAMEWINDOW_SYSTEM_DEFAULT GLFW)
endif()

set(GAMEWINDOW_SYSTEM ${GAMEWINDOW_SYSTEM_DEFAULT} CACHE STRING "The implementation to use for windows - EGLUT or GLFW")